### PR TITLE
bump version to 0.14.3

### PR DESCRIPTION
**Pull request by mrocklin**
also add license file to meta.yaml

### CODE REVIEW

**Comment by mrocklin** [comment]
Should I be concerned that appveyor hasn't shown up yet?

**Comment by jakirkham** [comment]
I have triggered AppVeyor manually. It does periodically struggle with rate limits. Have mentioned this to the AppVeyor team, but it is unclear how it will be resolved at this time.

xref: https://github.com/appveyor/ci/issues/1002

**Comment by mrocklin** [comment]
Oh cool.  I didn't  know that you could do that.  Is there a way I can do this as well?  If not, and if you're willing, https://github.com/conda-forge/distributed-feedstock/pull/26 could use the same treatment

**Comment by jakirkham** [comment]
Sure, done.

Unfortunately not that I know of. Webhooks require admin access. Sometimes you can start a PR build in the AppVeyor interface. Normally that requires a build to have already happened on that PR though. Can always resort to the typical close/open or push force as well.

**Comment by mrocklin** [comment]
Thank you @jakirkham for pushing appveyor through on both.

**Comment by jakirkham** [comment]
np

**Pull request merged**
