### PR TITLE
bump version to 0.11.1

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jakirkham** [comment]
Please [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` version `1.3.2` before proceeding with this or any other PR. This is needed to fix an issue where Travis CI bumped us from OS X version 10.9 to 10.11.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/249

**Comment by jakirkham** [comment]
Make sure to run `git add -A` to capture new files that have been added, but are not tracked.

**Comment by mrocklin** [comment]
amended

**Comment by alimanfoo** [comment]
CI error:

```
===== testing package: dask-0.11.1-py34_0 =====
import: 'dask'
import: 'dask.array'
import: 'dask.bag'
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 32, in <module>
    import dask.bag
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/dask/bag/__init__.py", line 3, in <module>
    from .core import (Bag, Item, from_sequence, from_url, to_textfiles, concat,
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/dask/bag/core.py", line 40, in <module>
    from ..bytes.core import write_bytes
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/dask/bytes/__init__.py", line 9, in <module>
    from . import s3
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/dask/bytes/s3.py", line 5, in <module>
    from s3fs import S3FileSystem
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/s3fs/__init__.py", line 1, in <module>
    from .core import S3FileSystem, S3File
  File "/Users/travis/miniconda3/envs/_test/lib/python3.4/site-packages/s3fs/core.py", line 23, in <module>
    trans.ReadTimeoutError, trans.IncompleteReadError
AttributeError: 'module' object has no attribute 'ReadTimeoutError'
TESTS FAILED: dask-0.11.1-py34_0
```

Weird because only occurs on travis PY34 and appveyor PY27, maybe some transient thing?

**Comment by jakirkham** [comment]
FYI the AppVeyor Python 2.7 failure is due to a subtle Windows specific issue related to the `%PATH%` length. Discussion and related PRs/issues can be found by following the linked issue.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/252

**Pull request closed without merging**
