### PR TITLE
bump version to 0.17.2

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by jakirkham** [comment]
Could we please add `numpy >=1.10.4` to match the recently declared `numpy` version constraint?

**Comment by jakirkham** [comment]
Ack, sorry, also please reset the build number to 0.

**Comment by mrocklin** [comment]
Ah, my mistake.  Resolved.

**Comment by jakirkham** [comment]
Thanks @mrocklin.

**Pull request merged**
