### PR TITLE
Add setuptools to build dependencies

### PR DESCRIPTION
**Pull request by koverholt**

### CODE REVIEW

**Comment by pelson** [comment]
Hi @koverholt. Just out of interest, are those build dependencies really necessary or are they just duplications of the run dependencies?

**Comment by koverholt** [comment]
They are just duplications of the run dependencies. I started this bad habit when maintaining multiple recipes where some recipes depended on others in the same directory, and I needed to have the other recipes listed in the dependencies section so they would get built recursively.

I like how things are isolated in conda-forge and now I can break my bad habits. :) So I'll clean up this recipe shortly. Thanks for the ping.

**Comment by koverholt** [comment]
Cleaned up the recipe in #2.

**Comment by pelson** [comment]
> I started this bad habit when maintaining multiple recipes where some recipes depended on others in the same directory, and I needed to have the other recipes listed in the dependencies section so they would get built recursively.

Oh man! I remember that now - conda-build didn't recurse properly for runtime dependencies, right? I wrote conda-build-all partially because of that (and the fact that I wanted build matrices).

Thanks for the feedback, and great stuff!

**Pull request merged**
