### PR TITLE
Bump minimum fsspec to 0.6.0

### LINKED ISSUE #90: Update minimum fsspec version in next release
We updated our minimum version of `fsspec` in https://github.com/dask/dask/pull/5588 to be `>=0.6.0`. This is just a reminder to update here when we do the next release

### PR DESCRIPTION
**Pull request by jrbourbeau**
Closes #90

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrocklin** [comment]
Ah.  My mistake.  I totally forgot about this, despite the fact that you
mentioned it just yesterday.

**Comment by jrbourbeau** [comment]
Not a problem, thank you for pushing out the new release : )

**Comment by jakirkham** [comment]
Went ahead and marked `dask-2.8.0-py_0.tar.bz2` as `broken`.

**Comment by jrbourbeau** [comment]
Nice, thank you @jakirkham. For future reference, how does one mark things as `broken`?

**Comment by jakirkham** [comment]
By asking core to do it for you. 😂

Unfortunately we don't have a good way to share this functionality more broadly. Definitely would be nice to confer these bits somehow.

**Pull request merged**
