### PR TITLE
Release 1.0.0

### PR DESCRIPTION
**Pull request by jakirkham**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mrocklin** [comment]
Should we wait for https://github.com/conda-forge/distributed-feedstock/pull/71 and pin that as well?

I find that otherwise people complain when they `conda install dask` and still get known bugs that were fixed a while ago.

**Comment by jakirkham** [comment]
Did the `distributed` requirement change in `setup.py`? If so, yes. If not, I don't think we should deviate; lest people get confused by discrepancy between the PyPI and conda-forge packages.

**Comment by jakirkham** [comment]
My understanding of the purpose of the `dask` package was to provide the [optional dependencies from `dask`]( https://github.com/dask/dask/blob/1.0.0/setup.py#L11-L16 ) and `distributed` (though IDK where the latter are listed). The more we deviate from that the more we risk confusing users that are running `pip install 'dask[extras]'` and `conda install dask`.

**Comment by mrocklin** [comment]
That is not my personal goal for the package.  My goal for the dask metapackage is for it to be the recommended way for novice users to install dask and have a good experience.  I would rather tell people "just conda install dask" rather than tell them "conda install both the dask and distributed libraries, oh, and also bokeh if you want the dashbaord".

**Comment by jakirkham** [comment]
Agree that is a desirable goal.

Would encourage trying to achieve that goal whether or not the user chose to install with Conda or Pip though. Especially for the sake of new users, who may not appreciate the differences between the two. If not for ourselves, when we choose to switch between one or the other for different reasons.

**Comment by mrocklin** [comment]
OK, so it sounds like you're suggesting bumping up the requirements in setup.py to suggested versions rather than strict requirements.  This seems against common practice, where people tend to try to be as permissive as possible in requirements.txt and setup.py.

The way I see it is that conda metapackages give us a capability that isn't present in pip.

**Comment by mrocklin** [comment]
I've tenatively pushed a commit that bumps the distributed version to 1.25.0

**Comment by mrocklin** [comment]
I'm going to merge this in for now.  I apologize for forcing the issue.  I just want to get something out soonish so people don't download partial solutions.  We should continue this conversation generally though (I'll open an issue).  We can revert the change if people agree that that's the right approach.

**Comment by mrocklin** [comment]
https://github.com/dask/dask/issues/4257

**Comment by jakirkham** [comment]
No worries. That seems reasonable. We can certainly discuss over there.

> We've been doing this for a while...

Thanks for pointing this out. I think I may have missed this was already happening.

**Comment by mrocklin** [comment]
My guess is that it got updated or not depending on which of us updated
this recipe :)

**Pull request merged**
