### PR TITLE
Release 2022.04.0

### PR DESCRIPTION
**Pull request by jsignell**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jsignell** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
Do we want to pick up this change ( https://github.com/conda-forge/dask-feedstock/pull/176 )?

**Comment by jsignell** [comment]
I can't tell from https://github.com/dask/distributed/issues/6025 if #176 was opened as a suggestion or whether it was intended to be merged. I am open to adding lz4 - no real opinion, so I'll wait for someone else to :+1: it. @mrocklin @jrbourbeau

**Comment by jsignell** [comment]
Either way it shouldn't block this, since we can always rebuild with that added dep if we want.

**Comment by mrocklin** [comment]
I've just merged it

**Comment by jsignell** [comment]
I rebased this PR off main and bumped the build back down.

**Comment by jrbourbeau** [comment]
Bumping CI...

**Comment by jakirkham** [comment]
Thanks all! 😄

**Pull request merged**
